# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ppage-service
spec:
  selector:
    app: ppage-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP